// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://hmspqehficzhnejhblgp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhtc3BxZWhmaWN6aG5lamhibGdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MTY1MjMsImV4cCI6MjA2NjM5MjUyM30.jhH3UYcN6TV_O5pnMNQIP0asWQScJsorb1Cm6488FUg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
);
